stages:
  - auto-release
  - build-release
  - create-release

auto-release:
  stage: auto-release
  image: ubuntu:latest
  only:
    - master
  before_script:
    - apt-get update && apt-get install -y git
    - git config user.name "gitlab-ci"
    - git config user.email "gitlab-ci@gitlab.com"
  script:
    - DATE_TAG=$(date +v%Y.%m.%d-%H%M)
    - "echo Generated tag: $DATE_TAG"
    - git tag $DATE_TAG
    - git push https://gitlab-ci-token:${CI_JOB_TOKEN}@${CI_SERVER_HOST}/${CI_PROJECT_PATH}.git $DATE_TAG

build-release:
  stage: build-release
  image: ubuntu:latest
  only:
    - tags
  parallel:
    matrix:
      - PLATFORM: [ win32, linux ]
  before_script:
    - apt-get update && apt-get install -y $([ "$PLATFORM" = "win32" ] && echo "mingw-w64") curl
    - curl -fsSL https://deb.nodesource.com/setup_24.x | bash -
    - apt-get install -y nodejs
  script:
    - npm i <<< $PLATFORM
    - npm run publish:$PLATFORM
  artifacts:
    paths:
      - publish/

release:
  stage: create-release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  only:
    - tags
  script:
    - echo "Creating release for $CI_COMMIT_TAG"
  release:
    tag_name: $CI_COMMIT_TAG
    name: 'Release $CI_COMMIT_TAG'
    description: 'Automated release for $CI_COMMIT_TAG'
    assets:
      links:
        - name: seraphimcms-linux-installer
          url: https://$CI_SERVER_HOST/$CI_PROJECT_PATH/-/jobs/artifacts/$CI_COMMIT_TAG/raw/publish/seraphimcms-linux-installer?job=build-release%3A%20%5Blinux%5D
          link_type: other
        - name: seraphimcms-win32-installer.exe
          url: https://$CI_SERVER_HOST/$CI_PROJECT_PATH/-/jobs/artifacts/$CI_COMMIT_TAG/raw/publish/seraphimcms-win32-installer.exe?job=build-release%3A%20%5Bwin32%5D
          link_type: other
