name: Build project for Release

on:
  release:
    types: [ published ]

permissions:
  contents: write

jobs:
  build-project-release:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        platform: [ linux, win32 ]

    steps:
      - uses: actions/checkout@v4
      - uses: egor-tensin/setup-mingw@v3

      - name: Build project
        run: |
          npm i <<< ${{ matrix.platform }}
          npm run publish:${{ matrix.platform }}

      - name: Upload project to release
        uses: softprops/action-gh-release@v1
        with:
          files: publish/seraphimcms-${{ matrix.platform }}-installer${{ matrix.platform == 'win32' && '.exe' || '' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}